# Generated by Django 5.1 on 2024-09-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turf", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievements",
            old_name="achievements_date",
            new_name="date",
        ),
    ]
